### ISSUE TITLE
Critical lack of humor

### ISSUE THREAD

**Issue by sudobash1** [v-rob/node-341#1]
Cheesecake is not nearly as funny as you think it is. I would suggest pineapple upside-down cake instead.

**Comment by v-rob** [comment]
However, Dr. Nuxoll is in control here--Le Roach does not control the homework assignment requirements as he does the Dogbot door controls, so pineapple upside-down cake is out of the question.  Had Le Roach been in control of this assignment, I'm sure we would have found a bug in the program, and would have had to check all our variables and track down all the stray pixels.
